
namespace :app do
  desc "Create a new app"

  task :init do
    sh "bundle init"
    sh "bundle add rspec"
    sh "rspec --init"
    sh "touch app.rb"
    sh "git init"
    sh "echo 'Gemfile.lock' >> .gitignore"
    sh "git add . :^Gemfile.lock && git commit -m 'Initial commit'"
  end
end
